# Generated by Django 3.1.3 on 2020-11-16 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('submitted_on', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_selected', models.BooleanField(blank=True, default=False, null=True, verbose_name='Selected Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('course_desc', models.TextField(blank=True, max_length=100, null=True, verbose_name='Course Description')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(max_length=3, unique=True)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=40, unique=True)),
                ('qn_mark', models.FloatField(blank=True, default=4, null=True)),
                ('neg_mark', models.FloatField(blank=True, default=1, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('time_limit', models.DurationField(help_text='HH:MM:SS format')),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('course_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.course', verbose_name='Course')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_text', models.TextField(max_length=200, verbose_name='Question Description')),
                ('qn_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Question Image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('exams', models.ManyToManyField(to='stud_app.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(help_text='10-digit phone number', max_length=10, unique=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('course_fk', models.ManyToManyField(to='stud_app.Course')),
                ('dept_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dept_fk__dept_name'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.attendee')),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stud_app.choice')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stud_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(help_text='10-digit phone number', max_length=10, unique=True)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('course_fk', models.ManyToManyField(to='stud_app.Course')),
                ('dept_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dept_fk__dept_name'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='dept_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.department'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.question'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='exam_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.exam'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='student_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.student'),
        ),
    ]
