# Generated by Django 3.1.3 on 2020-11-07 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stud_app.thumbs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6, unique=True)),
                ('course_name', models.CharField(max_length=50)),
                ('course_desc', models.TextField(max_length=100, verbose_name='Course Description')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(max_length=3, unique=True)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=40)),
                ('time_limit', models.DurationField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('course_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.course', verbose_name='Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_text', models.TextField(max_length=200, verbose_name='Question Description')),
                ('qn_image', stud_app.thumbs.ImageWithThumbsField(upload_to='img/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('course_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.course', verbose_name='Course')),
                ('exams', models.ManyToManyField(to='stud_app.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.TextField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, help_text='10-digit phone number only', max_length=10, null=True, unique=True)),
                ('course_fk', models.ManyToManyField(to='stud_app.Course')),
                ('dept_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usserrr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.question')),
                ('exam_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.exam')),
                ('student_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.student')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='qn_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.questiontag', verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='course',
            name='dept_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.department'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.question')),
            ],
        ),
    ]
