# Generated by Django 3.1.3 on 2020-11-02 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.course', verbose_name='Belongs to')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_text', models.CharField(max_length=200, verbose_name='Question Description')),
                ('qn_image', models.ImageField(upload_to='', verbose_name='Question Image')),
                ('qn_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.questionbank', verbose_name='IN QNbank')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.question')),
            ],
        ),
    ]
