# Generated by Django 3.1.3 on 2020-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Question Image'),
        ),
    ]
