# Generated by Django 3.1.3 on 2020-11-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0002_auto_20201108_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(blank=True, help_text='10-digit phone number', max_length=10, null=True, unique=True),
        ),
    ]
