# Generated by Django 3.1.3 on 2020-11-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0004_auto_20201102_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qn_text',
            field=models.TextField(max_length=200, verbose_name='Question Description'),
        ),
    ]
