# Generated by Django 3.1.3 on 2020-11-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0004_auto_20201111_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.FloatField(blank=True, null=True)),
                ('exam_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.exam')),
                ('student_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.choice')),
                ('list_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.attendee')),
            ],
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
