# Generated by Django 3.1.3 on 2020-11-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0005_auto_20201102_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn_image',
            field=models.ImageField(upload_to='images/', verbose_name='Question Image'),
        ),
    ]
