# Generated by Django 3.1.3 on 2020-11-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0005_auto_20201113_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_selected',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Correct Answer'),
        ),
    ]
