# Generated by Django 3.1.3 on 2020-11-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0006_choice_is_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='list_fk',
            new_name='attendee_fk',
        ),
    ]
