# Generated by Django 3.1.3 on 2020-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0007_auto_20201114_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='neg_mark',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='qn_mark',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
