# Generated by Django 3.1.3 on 2020-11-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0008_auto_20201114_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='neg_mark',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='qn_mark',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
