# Generated by Django 3.1.3 on 2020-11-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0008_auto_20201102_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=40)),
                ('time_limit', models.TimeField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Published')),
                ('course_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.course', verbose_name='Course')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='exams',
            field=models.ManyToManyField(to='stud_app.Exam'),
        ),
    ]
