# Generated by Django 3.1.3 on 2020-11-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0009_auto_20201114_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
