# Generated by Django 3.1.3 on 2020-11-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0010_auto_20201115_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
