# Generated by Django 3.1.3 on 2020-11-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0011_student_year_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='submitted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
