# Generated by Django 3.1.3 on 2020-11-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0012_attendee_submitted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='qn_tag',
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
    ]
