# Generated by Django 3.1.3 on 2020-11-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0012_results_student_fk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Results',
            new_name='Result',
        ),
    ]
