# Generated by Django 3.1.3 on 2020-11-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0013_auto_20201102_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
