# Generated by Django 3.1.3 on 2020-11-15 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0014_exam_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_selected',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Selected Answer'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='neg_mark',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='qn_mark',
            field=models.FloatField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.DurationField(help_text='HH:MM:SS format'),
        ),
    ]
