# Generated by Django 3.1.3 on 2020-11-03 04:34

from django.db import migrations
import stud_app.thumbs


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0015_auto_20201103_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn_image',
            field=stud_app.thumbs.ImageWithThumbsField(upload_to='img/'),
        ),
    ]
