# Generated by Django 3.1.3 on 2020-11-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0016_auto_20201103_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_fk',
            field=models.ManyToManyField(to='stud_app.Course'),
        ),
    ]
