# Generated by Django 3.1.3 on 2020-11-15 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0016_remove_exam_course_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course_fk',
        ),
        migrations.AddField(
            model_name='exam',
            name='course_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.course', verbose_name='Course'),
        ),
    ]
