# Generated by Django 3.1.3 on 2020-11-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0017_auto_20201103_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course_fk',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
