# Generated by Django 3.1.3 on 2020-11-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0019_auto_20201115_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['dept_fk__dept_name']},
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='year_joined',
            new_name='joined_on',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year_joined',
            new_name='joined_on',
        ),
    ]
