# Generated by Django 3.1.3 on 2020-11-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0020_auto_20201103_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stud_app.department'),
        ),
    ]
