# Generated by Django 3.1.3 on 2020-11-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0021_student_dept_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_fk',
            field=models.ManyToManyField(to='stud_app.Course'),
        ),
    ]
