# Generated by Django 3.1.3 on 2020-11-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0022_student_course_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
